allowBuilds:
  '@google/genai': true
  core-js: true
  esbuild: true
  protobufjs: true
  vue-demi: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - postcss
  - '@biomejs/biome@2.5.1'
  - '@biomejs/cli-darwin-arm64@2.5.1'
  - '@biomejs/cli-darwin-x64@2.5.1'
  - '@biomejs/cli-linux-arm64-musl@2.5.1'
  - '@biomejs/cli-linux-arm64@2.5.1'
  - '@biomejs/cli-linux-x64-musl@2.5.1'
  - '@biomejs/cli-linux-x64@2.5.1'
  - '@biomejs/cli-win32-arm64@2.5.1'
  - '@biomejs/cli-win32-x64@2.5.1'
  - '@sentry/browser-utils@10.60.0'
  - '@sentry/browser@10.60.0'
  - '@sentry/core@10.60.0'
  - '@sentry/feedback@10.60.0'
  - '@sentry/replay-canvas@10.60.0'
  - '@sentry/replay@10.60.0'
  - '@sentry/vue@10.60.0'
  - '@vitejs/plugin-legacy@8.1.0'
  - vite@8.1.0
